# podman compose --env-file .env.docker up -d --build
services:
  postgres:
    image: docker.io/library/postgres:18.3
    container_name: supermarket-db
    restart: unless-stopped
    env_file:
      - ./.env.docker
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - supermarket_db:/var/lib/postgresql
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: supermarket-api
    env_file:
      - ./.env.docker
    environment:
      DB_HOST: postgres  # Use service name for internal networking
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - postgres

volumes:
  supermarket_db:

networks:
  app_network:
    driver: bridge