BEGIN;

SET my.previous = 'Initial creation';
SET my.current  = '20251229_0_PrepareDatabaseVersion'; -- filename

CREATE TABLE IF NOT EXISTS database_version
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    current_version  VARCHAR(50) NOT NULL UNIQUE,
    previous_version VARCHAR(50) NOT NULL UNIQUE,
    executed_on      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO database_version (current_version, previous_version)
VALUES (current_setting('my.current')::VARCHAR(50), current_setting('my.previous')::VARCHAR(50));

COMMIT;