BEGIN;

-- INSTRUCTIONS:
-- copy this file into a new migration file
-- modify the values of my.previous and my.current
-- put your migration in between the big commented blocks
SET my.previous = '20251231_0_AlterUserTable'; -- change this
SET my.current  = '20260101_0_CreateProductRelatedTables'; -- filename

-- sanity check and validation
DO $$
DECLARE
    latest_current_version VARCHAR(50);
BEGIN
    SELECT current_version INTO latest_current_version
    FROM database_version
    ORDER BY id DESC LIMIT 1;

    IF latest_current_version != current_setting('my.previous') THEN
            RAISE EXCEPTION 'Migration version mismatch: expected %, got %',
                current_setting('my.previous'),
                latest_current_version;
    END IF;
END $$;


-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
-- YOUR MIGRATION CODE GOES BELOW THIS LINE
-- vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv


CREATE TABLE product_categories
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_on  TIMESTAMP    NOT NULL,
    created_by  VARCHAR(30)  NOT NULL,
    modified_on TIMESTAMP,
    modified_by VARCHAR(30)
);


CREATE TABLE products
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id  INTEGER        NOT NULL,
    name         VARCHAR(50)    NOT NULL,
    metadata_xml XML,
    price        NUMERIC(10, 2) NOT NULL,
    quantity     INTEGER        NOT NULL,
    status       INTEGER        NOT NULL,
    expiry_date  TIMESTAMP,
    created_on   TIMESTAMP      NOT NULL,
    created_by   VARCHAR(30)    NOT NULL,
    modified_on  TIMESTAMP,
    modified_by  VARCHAR(30),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES product_categories (id)
);

-- Create indexes for better query performance
CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_products_category_id ON products (category_id);


-- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-- YOUR MIGRATION CODE GOES ABOVE THIS LINE
-- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

-- update database version
INSERT INTO database_version (current_version, previous_version)
VALUES (current_setting('my.current')::VARCHAR(50), current_setting('my.previous')::VARCHAR(50));


COMMIT;